version: '3.3'

services:

  postgres-db:
    image: postgres:12
    ports:
    - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-pw
    secrets:
      - postgres-pw

  adminer:
    image: adminer:4.7.7
    ports:
      - "8081:8080"

secrets:
  postgres-pw:
    external: true

volumes:
  postgresql-data:
